import {
  CategorizerStrategy,
  CategorizationResult,
} from '../../interfaces/categorizer-strategy.interface';
import { TransactionCategory } from '../../../transactions/transaction.entity';

interface CategoryRule {
  category: TransactionCategory;
  patterns: RegExp[];
  keywords: string[];
}

export class RegexCategorizerStrategy implements CategorizerStrategy {
  readonly name = 'regex';

  private rules: CategoryRule[] = [
    {
      category: TransactionCategory.RENT,
      patterns: [/^rent/i, /^rental/i, /property\s*rent/i],
      keywords: ['rent', 'apartment'],
    },
    {
      category: TransactionCategory.SHOPPING,
      patterns: [
        /^amazon/i,
        /^walmart/i,
        /^target/i,
        /^costco/i,
        /^best\s*buy/i,
        /^nordstrom/i,
        /^macy/i,
      ],
      keywords: [
        'amazon',
        'walmart',
        'target',
        'costco',
        'shopping',
        'mall',
        'nordstrom',
        'macy',
      ],
    },
    {
      category: TransactionCategory.TRIP,
      patterns: [
        /^airbnb/i,
        /^hotel/i,
        /^flight/i,
        /^expedia/i,
        /^booking\.com/i,
        /^airline/i,
        /^southwest/i,
        /^united/i,
        /^delta/i,
        /^american\s*air/i,
        /^jetblue/i,
        /^travel/i,
        /^trip/i,
      ],
      keywords: [
        'airbnb',
        'hotel',
        'flight',
        'expedia',
        'booking',
        'airline',
        'travel',
        'trip',
        'vacation',
        'motel',
      ],
    },
    {
      category: TransactionCategory.GROCERY,
      patterns: [
        /^whole\s*foods/i,
        /^trader\s*joes/i,
        /^sprouts/i,
        /^aldi/i,
        /^publix/i,
        /^kroger/i,
        /^safeway/i,
        /^wegmans/i,
        /^food\s*lion/i,
      ],
      keywords: [
        'grocery',
        'whole foods',
        'trader joe',
        'sprouts',
        'aldi',
        'publix',
        'kroger',
        'safeway',
        'wegmans',
        'food lion',
        'supermarket',
      ],
    },
    {
      category: TransactionCategory.UBER,
      patterns: [/^uber/i, /^lyft/i, /^ride\s*share/i, /^via\s+ride/i],
      keywords: ['uber', 'lyft', 'rideshare', 'ride share'],
    },
    {
      category: TransactionCategory.EATING_OUT,
      patterns: [
        /^doordash/i,
        /^ubereats/i,
        /^grubhub/i,
        /^postmates/i,
        /^chipotle/i,
        /^mcdonald/i,
        /^starbucks/i,
        /^dunkin/i,
        /^subway/i,
        /^panera/i,
        /^pizza/i,
        /^sushi/i,
        /^restaurant/i,
        /^cafe/i,
        /^diner/i,
        /^bistro/i,
      ],
      keywords: [
        'doordash',
        'ubereats',
        'grubhub',
        'postmates',
        'chipotle',
        'mcdonald',
        'starbucks',
        'dunkin',
        'subway',
        'panera',
        'pizza',
        'sushi',
        'restaurant',
        'cafe',
        'diner',
        'bistro',
        'pho',
        'ramen',
        'burrito',
        'taco',
        'sandwich',
        'dining',
        'lunch',
        'dinner',
        'breakfast',
      ],
    },
    {
      category: TransactionCategory.PHONE_BILL,
      patterns: [
        /^t-mobile/i,
        /^verizon/i,
        /^at&t/i,
        /^sprint/i,
        /^tmobile/i,
        /^phone\s*bill/i,
        /^cellular/i,
      ],
      keywords: [
        't-mobile',
        'tmobile',
        'verizon',
        'at&t',
        'sprint',
        'phone bill',
        'cellular',
        'mobile',
      ],
    },
    {
      category: TransactionCategory.WIFI,
      patterns: [
        /^comcast/i,
        /^xfinity/i,
        /^spectrum/i,
        /^verizon\s*fios/i,
        /^att\s*internet/i,
        /^internet/i,
        /^wifi/i,
      ],
      keywords: [
        'comcast',
        'xfinity',
        'spectrum',
        'fios',
        'internet',
        'wifi',
        'broadband',
        'cable',
      ],
    },
    {
      category: TransactionCategory.SUBSCRIPTION,
      patterns: [
        /^netflix/i,
        /^spotify/i,
        /^hulu/i,
        /^disney\+/i,
        /^hbomax/i,
        /^hbo\s*max/i,
        /^max\s*\(/i,
        /^apple\s*tv/i,
        /^paramount\+/i,
        /^peacock/i,
        /^youtube\s*premium/i,
        /^youtube\s*music/i,
        /^audible/i,
        /^icloud\+/i,
        /^patreon/i,
      ],
      keywords: [
        'netflix',
        'spotify',
        'hulu',
        'disney',
        'hbomax',
        'hbo max',
        'apple tv',
        'paramount',
        'peacock',
        'youtube premium',
        'audible',
        'icloud',
        'patreon',
        'subscription',
        'membership',
      ],
    },
    {
      category: TransactionCategory.ELECTRICITY,
      patterns: [
        /^electric/i,
        /^power/i,
        /^utility/i,
        /^pge/i,
        /^con\s*ed/i,
        /^edison/i,
        /^duke\s*energy/i,
      ],
      keywords: [
        'electric',
        'power',
        'utility',
        'pge',
        'con ed',
        'edison',
        'energy',
      ],
    },
    {
      category: TransactionCategory.GAS,
      patterns: [
        /^shell/i,
        /^exxon/i,
        /^chevron/i,
        /^bp\b/i,
        /^mobil/i,
        /^speedway/i,
        /^7-eleven/i,
        /^gas$/i,
        /^gas\s/i,
      ],
      keywords: [
        'shell',
        'exxon',
        'chevron',
        'bp',
        'mobil',
        'speedway',
        'gas station',
        'gasoline',
      ],
    },
    {
      category: TransactionCategory.PERSONAL,
      patterns: [
        /^zara/i,
        /^uniqlo/i,
        /^h&m/i,
        /^gap\b/i,
        /^nike/i,
        /^adidas/i,
        /^clothing/i,
        /^apparel/i,
      ],
      keywords: [
        'zara',
        'uniqlo',
        'h&m',
        'gap',
        'nike',
        'adidas',
        'clothing',
        'apparel',
        'fashion',
        'wear',
        'outfit',
      ],
    },
    {
      category: TransactionCategory.TRANSIT,
      patterns: [
        /^metro/i,
        /^mta/i,
        /^bus\b/i,
        /^subway/i,
        /^train/i,
        /^transit/i,
        /^commute/i,
        /^parking/i,
        /^toll/i,
      ],
      keywords: [
        'metro',
        'mta',
        'bus',
        'subway',
        'train',
        'transit',
        'commute',
        'parking',
        'toll',
        'ferry',
      ],
    },
    {
      category: TransactionCategory.ONE_TIME,
      patterns: [
        /^irs/i,
        /^tax/i,
        /^refund/i,
        /^insurance/i,
        /^repair/i,
        /^maintenance/i,
      ],
      keywords: [
        'tax',
        'irs',
        'refund',
        'insurance',
        'repair',
        'maintenance',
        'fee',
        'fine',
      ],
    },
    {
      category: TransactionCategory.GIFT,
      patterns: [/^gift/i, /^donation/i, /^charity/i, /^donate/i],
      keywords: ['gift', 'donation', 'charity', 'donate', 'present'],
    },
    {
      category: TransactionCategory.DOCTOR,
      patterns: [
        /^doctor/i,
        /^dr\b/i,
        /^medical/i,
        /^hospital/i,
        /^clinic/i,
        /^pharmacy/i,
        /^cvs/i,
        /^walgreens/i,
        /^dentist/i,
        /^optical/i,
        /^vision/i,
        /^health/i,
        /^copay/i,
      ],
      keywords: [
        'doctor',
        'medical',
        'hospital',
        'clinic',
        'pharmacy',
        'cvs',
        'walgreens',
        'dentist',
        'optical',
        'vision',
        'health',
        'copay',
        'prescription',
        'therapy',
      ],
    },
    {
      category: TransactionCategory.CAR,
      patterns: [
        /^auto/i,
        /^car\s/i,
        /^tire/i,
        /^oil\s*change/i,
        /^mechanic/i,
        /^autozone/i,
        /^oreilly/i,
        /^pep\s*boys/i,
      ],
      keywords: [
        'auto',
        'car',
        'tire',
        'oil change',
        'mechanic',
        'autozone',
        'oreilly',
        'pep boys',
        'repair',
        'maintenance',
      ],
    },
    {
      category: TransactionCategory.GAS_UTILITY,
      patterns: [
        /^gas\s*utility/i,
        /^natural\s*gas/i,
        /^gas\s*company/i,
        /^gas\s*bill/i,
      ],
      keywords: ['natural gas', 'gas utility', 'gas company', 'gas bill'],
    },
  ];

  categorize(description: string, _amount: number): CategorizationResult {
    void _amount;
    const desc = description.trim();

    for (const rule of this.rules) {
      for (const pattern of rule.patterns) {
        if (pattern.test(desc)) {
          return { category: rule.category, confidence: 0.9 };
        }
      }
    }

    const descLower = desc.toLowerCase();
    for (const rule of this.rules) {
      for (const keyword of rule.keywords) {
        if (descLower.includes(keyword.toLowerCase())) {
          return { category: rule.category, confidence: 0.7 };
        }
      }
    }

    return { category: TransactionCategory.ONE_TIME, confidence: 0.1 };
  }
}
